nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_50 -o brightwire_50.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_52 -o brightwire_52.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_53 -o brightwire_53.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_60 -o brightwire_60.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_61 -o brightwire_61.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_62 -o brightwire_62.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_70 -o brightwire_70.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_72 -o brightwire_72.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_75 -o brightwire_75.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_80 -o brightwire_80.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_86 -o brightwire_86.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_87 -o brightwire_87.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_89 -o brightwire_89.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_90 -o brightwire_90.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_100 -o brightwire_100.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_100 -o brightwire_103.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_100 -o brightwire_110.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_100 -o brightwire_120.ptx -allow-unsupported-compiler
nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_100 -o brightwire_121.ptx -allow-unsupported-compiler

nvcc brightwire.cu -use_fast_math -ptx -m 64 -arch sm_52 -o brightwire.ptx -allow-unsupported-compiler